name: Testing

on: [push]


jobs:
  job_1:
    runs-on: ubuntu-latest
    container: adnanmoussa/computational-workflows-homework:latest
    steps:
      - name: My first step
        uses: actions/checkout@v2
      - name: Run step
        run:  py.test-3
        

